// airlineIATA koduna göre airline adının alınması.
export function getAirlineNameByIATA(IATA) {
    const airlines = {
        "A2": "Cielos Airlines",
        "A3": "Aegean Airlines",
        "A4": "Southern Winds Airlines",
        "A5": "Air France Hop",
        "A6": "Air Alps Aviation",
        "A7": "Air Plus Comet",
        "A8": "Ameriflight",
        "A9": "Georgian Airways",
        "AA": "American Airlines",
        "AB": "Air Berlin",
        "AC": "Air Canada",
        "AD": "Azul Linhas Aéreas Brasileiras",
        "AE": "Mandarin Airlines",
        "AF": "Air France",
        "AG": "ASL Airlines Ireland",
        "AH": "Air Algérie",
        "AI": "Air India",
        "AJ": "Aero Contractors",
        "AK": "AirAsia",
        "AL": "Transaviaexport",
        "AM": "Aeroméxico",
        "AN": "Advanced Air",
        "AO": "Australian Airlines",
        "AP": "Air One",
        "AR": "Aerolíneas Argentinas",
        "AS": "Alaska Airlines",
        "AT": "Royal Air Maroc",
        "AU": "Austral Lineas Aereas",
        "AV": "Avianca",
        "AW": "CHC Airways",
        "AX": "Trans States Airlines",
        "AY": "Finnair",
        "AZ": "ITA Airways",
        "B2": "Belavia Belarusian Airlines",
        "B3": "Bellview Airlines",
        "B4": "Flyglobespan",
        "B5": "East African Safari Air Express",
        "B6": "JetBlue",
        "B7": "Uni Airways",
        "B8": "Eritrean Airlines",
        "B9": "Air Bangladesh",
        "BA": "British Airways",
        "BB": "Seaborne Airlines",
        "BC": "Skymark Airlines",
        "BE": "Flybe",
        "BF": "Aero-Service",
        "BG": "Biman Bangladesh Airlines",
        "BI": "Royal Brunei Airlines",
        "BJ": "Nouvel Air Tunisie",
        "BK": "Potomac Air",
        "BL": "Jetstar Pacific",
        "BM": "bmi regional",
        "BN": "Horizon Airlines",
        "BO": "Bouraq Indonesia Airlines",
        "BP": "Air Botswana",
        "BQ": "Bukovyna Airlines",
        "BR": "EVA Air",
        "BS": "British International Helicopters",
        "BT": "airBaltic",
        "BU": "SAS Braathens",
        "BV": "Blue Panorama Airlines",
        "BW": "Caribbean Airlines",
        "BX": "Air Busan",
        "BY": "TUI Airways",
        "BZ": "Blue Dart Aviation",
        "C0": "Centralwings",
        "C4": "Zimex Aviation",
        "C5": "CommutAir",
        "C6": "CanJet",
        "C7": "Rico Linhas Aéreas",
        "C9": "Cirrus Airlines",
        "CA": "Air China",
        "CC": "Air Atlanta Icelandic",
        "CE": "Nationwide Airlines",
        "CF": "China Postal Airlines",
        "CG": "Airlines PNG",
        "CH": "Bemidji Airlines",
        "CI": "China Airlines",
        "CJ": "China Northern Airlines",
        "CK": "China Cargo Airlines",
        "CL": "Lufthansa CityLine",
        "CM": "Copa Airlines",
        "CN": "Grand China Air",
        "CO": "Continental Airlines",
        "CP": "Compass Airlines",
        "CQ": "Sunshine Express Airlines",
        "CS": "Continental Micronesia",
        "CT": "Alitalia CityLiner",
        "CU": "Cubana de Aviación",
        "CV": "Cargolux",
        "CW": "Air Marshall Islands",
        "CX": "Cathay Pacific",
        "CY": "Cyprus Airways",
        "CZ": "China Southern Airlines",
        "D3": "Daallo Airlines",
        "D4": "Alidaunia",
        "D5": "Dauair",
        "D6": "Interair South Africa",
        "D7": "FlyAsianXpress",
        "D8": "Norwegian Air International",
        "D9": "Aeroflot-Don",
        "DA": "Air Georgia",
        "DB": "Brit Air",
        "DC": "Golden Air",
        "DD": "Nok Air",
        "DE": "Condor",
        "DG": "Tigerair Philippines",
        "DH": "Norwegian Air Norway",
        "DI": "dba",
        "DJ": "Polynesian Blue",
        "DK": "Thomas Cook Airlines Scandinavia",
        "DL": "Delta Air Lines",
        "DP": "First Choice Airways",
        "DR": "Air Méditerranée",
        "DS": "easyJet Switzerland",
        "DT": "TAAG Angola Airlines",
        "DU": "Norwegian Long Haul",
        "DV": "Nantucket Airlines",
        "DW": "Aero-Charter Ukraine",
        "DX": "DAT Danish Air Transport",
        "DY": "Norwegian Air Shuttle",
        "E0": "Eos Airlines",
        "E2": "Kampuchea Airlines",
        "E3": "Domodedovo Airlines",
        "E4": "Aero Asia International",
        "E5": "Samara Airlines",
        "E7": "Estafeta Carga Aerea",
        "E8": "Alpi Eagles",
        "E9": "Boston-Maine Airways",
        "EC": "easyJet Europe",
        "ED": "Airblue",
        "EE": "Aero Airlines",
        "EF": "Far Eastern Air Transport",
        "EG": "Japan Asia Airways",
        "EH": "ANA Wings",
        "EI": "Aer Lingus",
        "EJ": "New England Airlines",
        "EK": "Emirates",
        "EL": "Air Nippon",
        "EM": "Empire Airlines",
        "EN": "Air Dolomiti",
        "EO": "Hewa Bora Airways",
        "EP": "Iran Aseman Airlines",
        "EQ": "TAME",
        "ER": "Astar Air Cargo",
        "ES": "DHL International",
        "ET": "Ethiopian Airlines",
        "EU": "Ecuatoriana",
        "EV": "ExpressJet",
        "EW": "Eurowings",
        "EX": "Air Santo Domingo",
        "EY": "Etihad Airways",
        "EZ": "Sun Air of Scandinavia",
        "F2": "Fly Air",
        "F3": "Faso Airways",
        "F4": "Albarka Air",
        "F5": "Cosmic Air",
        "F6": "Faroejet",
        "F7": "Flybaboo",
        "F9": "Frontier Airlines",
        "FA": "Safair",
        "FB": "Bulgaria Air",
        "FC": "Finncomm Airlines",
        "FD": "Thai AirAsia",
        "FE": "Primaris Airlines",
        "FG": "Ariana Afghan Airlines",
        "FH": "Freebird Airlines",
        "FI": "Icelandair",
        "FJ": "Fiji Airways",
        "FK": "Africa West",
        "FL": "AirTran Airways",
        "FM": "Shanghai Airlines",
        "FO": "Airlines Of Tasmania",
        "FP": "Freedom Air",
        "FR": "Ryanair",
        "FS": "Flyr",
        "FT": "Siem Reap Airways",
        "FV": "Pulkovo Aviation Enterprise",
        "FW": "Ibex Airlines",
        "FX": "FedEx Express",
        "FY": "Northwest Regional Airlines",
        "FZ": "Flydubai",
        "G0": "Ghana International Airlines",
        "G2": "Avirex",
        "G3": "GOL Linhas Aéreas Inteligentes",
        "G4": "Allegiant Air",
        "G5": "China Express Airlines",
        "G6": "Guine Bissaur Airlines",
        "G7": "GoJet Airlines",
        "G8": "GoAir",
        "G9": "Air Arabia",
        "GA": "Garuda Indonesia",
        "GB": "ABX Air",
        "GC": "Gambia International Airlines",
        "GD": "Air Alpha Greenland",
        "GE": "TransAsia Airways",
        "GF": "Gulf Air",
        "GG": "Air Comores International",
        "GH": "Ghana Airways",
        "GI": "Longhao Airlines",
        "GJ": "Eurofly Service",
        "GK": "Jetstar Japan",
        "GL": "Air Greenland",
        "GM": "Air Slovakia",
        "GN": "Air Gabon",
        "GO": "Kuzu Airlines Cargo",
        "GP": "Gestair",
        "GQ": "Big Sky Airlines",
        "GR": "Aurigny Air Services",
        "GS": "Tianjin Airlines",
        "GT": "GB Airways",
        "GV": "Grant Aviation",
        "GW": "Kuban Airlines",
        "GX": "Jetx Airlines",
        "GY": "Tri-MG Intra Asia Airlines",
        "GZ": "Rotation International Air Services",
        "H2": "Sky Airline",
        "H5": "Mavial Magadan Airlines",
        "H6": "Hageland Aviation Services",
        "H8": "Dalavia",
        "H9": "Izair",
        "HA": "Hawaiian Airlines",
        "HB": "Greater Bay Airlines",
        "HC": "Aero-Tropics Air Services",
        "HD": "Air Do",
        "HE": "Luftfahrtgesellschaft Walter",
        "HG": "Niki",
        "HJ": "Asian Express Airlines",
        "HK": "Four Star Cargo",
        "HM": "Air Seychelles",
        "HN": "Heavylift Cargo Airlines",
        "HO": "Juneyao Airlines",
        "HP": "Pearl Airways",
        "HQ": "Thomas Cook Airlines Belgium",
        "HR": "Hahn Air",
        "HT": "Aeromist-Kharkiv",
        "HU": "Hainan Airlines",
        "HV": "Transavia",
        "HW": "North-Wright Airways",
        "HX": "Hong Kong Airlines",
        "HY": "Uzbekistan Airways",
        "HZ": "Sat Airlines",
        "I2": "Iberia Express",
        "I4": "Interstate Airline",
        "I5": "AirAsia India",
        "I6": "Sky Eyes",
        "I7": "Paramount Airways",
        "I9": "Central Airlines",
        "IA": "Iraqi Airways",
        "IB": "Iberia Airlines",
        "IC": "Indian Airlines",
        "ID": "Interlink Airlines",
        "IE": "Solomon Airlines",
        "IF": "Islas Airways",
        "IG": "Air Italy",
        "II": "IBC Airways",
        "IJ": "Great Wall Airlines",
        "IK": "Imair Airlines",
        "IM": "Menajet",
        "IN": "MAT Macedonian Airlines",
        "IO": "Indonesian Airlines",
        "IP": "Atyrau Air Ways",
        "IQ": "Augsburg Airways",
        "IR": "Iran Air",
        "IT": "Tigerair Taiwan",
        "IV": "Wind Jet",
        "IW": "AOM French Airlines",
        "IX": "Air India Express",
        "IY": "Yemenia",
        "IZ": "Arkia Israel Airlines",
        "J2": "Azerbaijan Airlines",
        "J3": "Northwestern Air",
        "J4": "Buffalo Airways",
        "J6": "Cruiser Linhas Aéreas",
        "J7": "Centre-Avia",
        "J8": "Berjaya Air",
        "J9": "Jazeera Airways",
        "JB": "Helijet",
        "JC": "JAL Express",
        "JE": "Mango",
        "JF": "L.A.B. Flying Service",
        "JH": "Fuji Dream Airlines",
        "JI": "Midway Airlines",
        "JJ": "TAM Brazilian Airlines",
        "JK": "Spanair",
        "JL": "Japan Airlines",
        "JM": "Air Jamaica",
        "JN": "Excel Airways",
        "JO": "JALways",
        "JP": "Adria Airways",
        "JQ": "Jetstar Airways",
        "JR": "Aero California",
        "JT": "Lion Air",
        "JU": "Air Serbia",
        "JV": "Bearskin Lake Air Service",
        "JW": "Vanilla Air",
        "JX": "STARLUX Airlines",
        "JY": "Air Turks and Caicos",
        "JZ": "Skyways Express",
        "K2": "Eurolot",
        "K4": "Kalitta Air",
        "K5": "Wings of Alaska",
        "K6": "Khalifa Airways",
        "K8": "Airlink Zambia",
        "K9": "Krylo Airlines",
        "KA": "Cathay Dragon",
        "KB": "Druk Air",
        "KC": "Air Astana",
        "KD": "Western Global Airlines",
        "KE": "Korean Air",
        "KF": "Blue1",
        "KG": "Key Lime Air",
        "KH": "Aloha Air Cargo",
        "KI": "Adam Air",
        "KJ": "British Mediterranean Airways",
        "KK": "Atlasjet",
        "KL": "KLM Royal Dutch Airlines",
        "KM": "Air Malta",
        "KN": "China United Airlines",
        "KO": "Alaska Central Express",
        "KP": "Kiwi International Air Lines",
        "KQ": "Kenya Airways",
        "KR": "Comores Airlines",
        "KS": "Peninsula Airways",
        "KU": "Kuwait Airways",
        "KV": "Sky Regional Airlines",
        "KX": "Cayman Airways",
        "KZ": "Nippon Cargo Airlines",
        "L1": "Total Linhas Aéreas",
        "L2": "Lynden Air Cargo",
        "L3": "LTU Austria",
        "L5": "Lufttransport",
        "L6": "Tbilaviamsheni",
        "L7": "Laoag International Airlines",
        "L8": "Air Luxor GB",
        "L9": "Teamline Air",
        "LA": "LATAM Chile",
        "LB": "Lloyd Aéreo Boliviano",
        "LD": "Linea Turistica Aerotuy",
        "LE": "Norwegian Air Sweden",
        "LF": "Contour Airlines",
        "LG": "Luxair",
        "LH": "Lufthansa",
        "LI": "Leeward Islands Air Transport",
        "LJ": "Jin Air",
        "LK": "Air Luxor",
        "LL": "Allegro",
        "LN": "Libyan Arab Airlines",
        "LO": "LOT Polish Airlines",
        "LP": "LAN Peru",
        "LQ": "Lebanese Air Transport",
        "LR": "LACSA",
        "LS": "Jet2.com",
        "LT": "LTU International",
        "LU": "LAN Express",
        "LV": "Albanian Airlines",
        "LW": "Pacific Wings",
        "LX": "Swiss International Air Lines",
        "LY": "El Al Israel Airlines",
        "LZ": "Belle Air",
        "M2": "Mahfooz Aviation",
        "M3": "ABSA - Aerolinhas Brasileiras",
        "M4": "Nova Airline",
        "M5": "Kenmore Air",
        "M6": "Amerijet International",
        "M7": "MasAir",
        "M9": "Motor Sich",
        "MA": "Malév Hungarian Airlines",
        "MB": "MNG Airlines",
        "MC": "Air Mobility Command",
        "MD": "Air Madagascar",
        "ME": "Middle East Airlines",
        "MF": "XiamenAir",
        "MG": "Champion Air",
        "MH": "Malaysia Airlines",
        "MI": "SilkAir",
        "MJ": "Líneas Aéreas Privadas Argentinas",
        "MK": "Air Mauritius",
        "MM": "Peach",
        "MN": "Comair",
        "MO": "Calm Air",
        "MP": "Martinair",
        "MQ": "Envoy Air",
        "MR": "Air Mauritanie",
        "MS": "EgyptAir",
        "MT": "Thomas Cook Airlines",
        "MU": "China Eastern Airlines",
        "MV": "Armenian International Airways",
        "MW": "Maya Island Air",
        "MX": "Breeze Airways",
        "MY": "Midwest Airlines",
        "MZ": "Merpati Nusantara Airlines",
        "N2": "Kabo Air",
        "N3": "Omskavia Airline",
        "N4": "Mountain Air Company",
        "N5": "Skagway Air Service",
        "N6": "Nuevo Continente",
        "N7": "National Airlines",
        "N8": "Fika Salaama Airlines",
        "N9": "Novair",
        "NB": "Sterling Airlines",
        "NC": "Northern Air Cargo",
        "NE": "SkyEurope",
        "NF": "Air Vanuatu",
        "NG": "Lauda Air",
        "NH": "All Nippon Airways",
        "NI": "Portugalia",
        "NK": "Spirit Airlines",
        "NL": "Shaheen Air International",
        "NM": "Air Madrid",
        "NN": "VIM Airlines",
        "NO": "Neos",
        "NQ": "Air Japan",
        "NR": "Pamir Airways",
        "NT": "Binter Canarias",
        "NU": "Japan Transocean Air",
        "NV": "Air Central",
        "NW": "Northwest Airlines",
        "NX": "Air Macau",
        "NY": "Air Iceland",
        "NZ": "Air New Zealand",
        "O3": "SF Airlines",
        "O6": "Avianca Brazil",
        "O7": "Ozjet Airlines",
        "O8": "Oasis Hong Kong Airlines",
        "OA": "Olympic Airlines",
        "OB": "Astrakhan Airlines",
        "OD": "Malindo Air",
        "OE": "Asia Overnight Express",
        "OG": "Play",
        "OH": "PSA Airlines",
        "OJ": "Overland Airways",
        "OK": "Czech Airlines",
        "OL": "Ostfriesische Lufttransport",
        "OM": "MIAT Mongolian Airlines",
        "OO": "SkyWest Airlines",
        "OR": "TUI fly Netherlands",
        "OS": "Austrian Airlines",
        "OT": "Aeropelican Air Services",
        "OU": "Croatia Airlines",
        "OV": "Estonian Air",
        "OW": "Executive Airlines",
        "OX": "Orient Thai Airlines",
        "OY": "Omni Air International",
        "OZ": "Asiana Airlines",
        "P5": "Copa Airlines Colombia",
        "P7": "Russian Sky Airlines",
        "P9": "Perm Airlines",
        "PA": "Florida Coastal Airlines",
        "PC": "Pegasus Airlines",
        "PD": "Porter Airlines",
        "PE": "Air Europe",
        "PF": "Palestinian Airlines",
        "PG": "Bangkok Airways",
        "PH": "Polynesian Airlines",
        "PJ": "Air Saint Pierre",
        "PK": "Pakistan International Airlines",
        "PL": "Aeroperú",
        "PM": "Tropic Air",
        "PO": "Polar Air Cargo",
        "PQ": "SkyUp",
        "PR": "Philippine Airlines",
        "PS": "Ukraine International Airlines",
        "PT": "Piedmont Airlines",
        "PU": "PLUNA",
        "PV": "PAN Air",
        "PW": "Precision Air",
        "PX": "Air Niugini",
        "PY": "Surinam Airways",
        "PZ": "TAM Mercosur",
        "Q3": "Zambian Airways",
        "Q5": "40-Mile Air",
        "Q6": "Aero Condor Peru",
        "Q8": "Pacific East Asia Cargo Airlines",
        "Q9": "Afrinat International Airlines",
        "QB": "Georgian National Airlines",
        "QC": "Air Corridor",
        "QE": "Crossair Europe",
        "QF": "Qantas",
        "QH": "Air Kyrgyzstan",
        "QI": "Cimber Air",
        "QK": "Air Canada Jazz",
        "QL": "Aero Lanka",
        "QM": "Air Malawi",
        "QN": "Air Armenia",
        "QO": "Aeromexpress",
        "QQ": "Alliance Airlines",
        "QR": "Qatar Airways",
        "QS": "Smartwings",
        "QT": "Tampa Cargo",
        "QV": "Lao Airlines",
        "QW": "Blue Wings",
        "QX": "Horizon Air",
        "QY": "European Air Transport Leipzig",
        "QZ": "Indonesia AirAsia",
        "R0": "Royal Airlines",
        "R2": "Orenburg Airlines",
        "R3": "Armenian Airlines",
        "R3": "Aircompany Yakutia",
        "R5": "Jordan Aviation",
        "R5": "Malta Air Charter",
        "R7": "Aserca Airlines",
        "R8": "Kyrgyzstan Airlines",
        "R9": "Camai Air",
        "RB": "Syrian Arab Airlines",
        "RB": "Air Srpska",
        "RC": "Atlantic Airways",
        "RD": "Ryan International Airlines",
        "RE": "Aer Arann",
        "RF": "Florida West International Airways",
        "RG": "VRG Linhas Aereas",
        "RH": "Republic Express Airlines",
        "RI": "Mandala Airlines",
        "RJ": "Royal Jordanian",
        "RK": "Royal Khmer Airlines",
        "RL": "Royal Flight",
        "RO": "Tarom",
        "RQ": "Kam Air",
        "RR": "Royal Air Force",
        "RS": "Royal Air Force of Oman",
        "RT": "RAK Airways",
        "RU": "AirBridgeCargo",
        "RV": "Air Canada Rouge",
        "RW": "Republic Airlines",
        "RX": "Aviaexpress",
        "S0": "Slok Air Gambia",
        "S2": "JetLite",
        "S3": "Santa Barbara Airlines",
        "S4": "SATA International",
        "S5": "Trast Aero",
        "S5": "Shuttle America",
        "S7": "S7 Airlines",
        "S8": "Shovkoviy Shlyah",
        "S8": "Chari Aviation Services",
        "SA": "South African Airways",
        "SB": "Air Caledonie International",
        "SC": "Shandong Airlines",
        "SD": "Sudan Airways",
        "SE": "XL Airways France",
        "SF": "Tassili Airlines",
        "SG": "SpiceJet",
        "SH": "Fly Me Sweden",
        "SI": "Skynet Airlines",
        "SJ": "Seagle Air",
        "SK": "Scandinavian Airlines",
        "SN": "Brussels Airlines",
        "SO": "Sosoliso Airlines",
        "SO": "Superior Aviation",
        "SP": "SATA Air Acores",
        "SQ": "Singapore Airlines",
        "SQ": "Singapore Airlines Cargo",
        "SS": "Corsair International",
        "ST": "Germania",
        "SU": "Aeroflot",
        "SV": "Saudi Arabian Airlines",
        "SW": "Air Namibia",
        "SX": "Skybus Airlines",
        "SY": "Sun Country Airlines",
        "T2": "TMA Cargo",
        "T3": "Eastern Airways",
        "T4": "Hellas Jet",
        "T6": "Tavrey Airlines",
        "T7": "Twin Jet",
        "T9": "Thai Star Airlines",
        "T9": "TransMeridian Airlines",
        "TA": "Avianca El Salvador",
        "TB": "TUI fly Belgium",
        "TC": "Air Tanzania",
        "TD": "Atlantis European Airways",
        "TD": "Tulip Air",
        "TE": "FlyLal",
        "TG": "Thai Airways",
        "TH": "Transmile Air Services",
        "TI": "Tol-Air Services",
        "TK": "Turkish Airlines",
        "TL": "Airnorth",
        "TM": "LAM Mozambique Airlines",
        "TN": "Air Tahiti Nui",
        "TO": "Transavia France",
        "TP": "TAP Air Portugal",
        "TQ": "Tandem Aero",
        "TR": "Scoot",
        "TS": "Air Transat",
        "TT": "Tigerair Australia",
        "TU": "Tunisair",
        "TV": "Virgin Express",
        "TW": "T'way Air",
        "TX": "Air Caraïbes",
        "TY": "Air Calédonie",
        "TZ": "ATA Airlines",
        "U2": "easyJet",
        "U3": "Avies",
        "U4": "PMTair",
        "U5": "USA3000 Airlines",
        "U6": "Ural Airlines",
        "U7": "USA Jet Airlines",
        "U8": "Armavia",
        "U9": "Tatarstan Airlines",
        "UA": "United Airlines",
        "UB": "Myanma Airways",
        "UE": "Nasair",
        "UF": "UM Airlines",
        "UG": "Tunisair Express",
        "UI": "Eurocypria Airlines",
        "UK": "Vistara",
        "UL": "SriLankan Airlines",
        "UM": "Air Zimbabwe",
        "UN": "Transaero Airlines",
        "UO": "HK Express",
        "UP": "Bahamasair",
        "US": "US Airways",
        "UT": "UTair Aviation",
        "UU": "Air Austral",
        "UX": "Air Europa",
        "UY": "Cameroon Airlines",
        "UZ": "El-Buraq Air Transport",
        "V0": "Conviasa",
        "V2": "Karat",
        "V3": "Carpatair",
        "V4": "Reem Air",
        "V5": "Avolar Aerolineas",
        "V5": "Royal Aruban Airline",
        "V7": "Air Senegal International",
        "V8": "ATRAN Cargo Airlines",
        "V9": "BAL Bashkirian Airlines",
        "VA": "Virgin Australia",
        "VB": "VivaAerobús",
        "VC": "Air Australia",
        "VC": "Voyageur Airways",
        "VD": "Henan Airlines",
        "VE": "EUjet",
        "VE": "Volare Airlines",
        "VE": "Avensa",
        "VF": "Valuair",
        "VG": "VLM Airlines",
        "VI": "Volga-Dnepr Airlines",
        "VJ": "VietJet Air",
        "VK": "Virgin Nigeria Airways",
        "VL": "Air VIA",
        "VM": "Viaggio Air",
        "VN": "Vietnam Airlines",
        "VO": "Austrian Arrows",
        "VP": "VASP",
        "VR": "TACV",
        "VS": "Virgin Atlantic Airways",
        "VT": "Air Tahiti",
        "VU": "Air Ivoire",
        "VV": "Aerosvit Airlines",
        "VW": "Aeromar",
        "VX": "Virgin America",
        "VY": "Vueling Airlines",
        "VZ": "Air Class Lineas Aereas",
        "W1": "WDL Aviation",
        "W2": "Canadian Western Airlines",
        "W3": "Flyhy Cargo Airlines",
        "W4": "Aero Services Executive",
        "W5": "Mahan Air",
        "W6": "Wizz Air",
        "W8": "Cargojet Airways",
        "W9": "Wizz Air UK",
        "WA": "KLM Cityhopper",
        "WB": "Rwandair Express",
        "WC": "Islena De Inversiones",
        "WD": "DAS Air Cargo",
        "WE": "Centurion Air Cargo",
        "WF": "Widerøe",
        "WG": "Sunwing Airlines",
        "WH": "China Northwest Airlines",
        "WJ": "WebJet Linhas Aéreas",
        "WK": "Edelweiss Air",
        "WN": "Southwest Airlines",
        "WO": "Swoop",
        "WQ": "iAero Airways",
        "WR": "Royal Tongan Airlines",
        "WS": "WestJet",
        "WT": "Wasaya Airways",
        "WV": "Swe Fly",
        "WW": "WOW air",
        "WX": "CityJet",
        "WY": "Oman Air",
        "WZ": "West African Airlines",
        "X3": "TUI fly Deutschland",
        "X7": "Chitaavia",
        "X9": "Avion Express",
        "XC": "Corendon Airlines",
        "XE": "JSX",
        "XF": "Vladivostok Air",
        "XG": "Clickair",
        "XJ": "Mesaba Airlines",
        "XK": "Corse-Mediterranee",
        "XL": "LATAM Ecuador",
        "XN": "Mexicana de Aviación",
        "XO": "LTE International Airways",
        "XO": "China Xinhua Airlines",
        "XP": "Avelo Airlines",
        "XQ": "SunExpress",
        "XS": "SITA",
        "XT": "Air Exel",
        "XW": "NokScoot",
        "XY": "flynas",
        "Y4": "Volaris",
        "Y5": "Pace Airlines",
        "Y8": "Suparna Airlines",
        "Y9": "Kish Air",
        "YG": "YTO Cargo Airlines",
        "YH": "West Caribbean Airways",
        "YI": "Air Sunshine",
        "YL": "Yamal Airlines",
        "YM": "Montenegro Airlines",
        "YP": "Air Premia",
        "YT": "Air Togo",
        "YU": "EuroAtlantic Airways",
        "YV": "Mesa Airlines",
        "YW": "Air Nostrum",
        "YX": "Midwest Airlines",
        "Z2": "AirAsia Zest",
        "Z3": "Avient Aviation",
        "Z4": "Zoom Airlines",
        "Z7": "ADC Airlines",
        "Z8": "Amaszonas",
        "Z9": "Bek Air",
        "ZA": "Interavia Airlines",
        "ZA": "Access Air",
        "ZB": "Air Bourbon",
        "ZB": "Monarch Airlines",
        "ZE": "Arcus-Air Logistic",
        "ZE": "Lineas Aereas Azteca",
        "ZH": "Shenzhen Airlines",
        "ZI": "Aigle Azur",
        "ZK": "Great Lakes Airlines",
        "ZL": "Regional Express",
        "ZP": "Silk Way Airlines",
        "ZS": "Azzurra Air",
        "ZS": "Sama Airlines",
        "ZT": "Titan Airways",
        "ZU": "Helios Airways",
        "ZV": "Air Midwest",
        "ZW": "Air Wisconsin",
        "ZX": "Air Georgian",
        "04": "Antrak Air",
        "0A": "Amber Air",
        "0B": "Blue Air",
        "0D": "Darwin Airline",
        "0J": "Jetclub",
        "1A": "Amadeus Global Travel Distribution",
        "1I": "NetJets",
        "1L": "Open Skies Consultative Commission",
        "1T": "1Time Airline",
        "1W": "Wings Air",
        "20": "Air Salone",
        "2B": "Aerocondor",
        "2D": "Eastern Airlines",
        "2F": "Frontier Flying Service",
        "2G": "Cargoitalia",
        "2J": "Air Burkina",
        "2K": "Aerogal",
        "2L": "Helvetic Airways",
        "2M": "Moldavian Airlines",
        "2N": "Yuzhmashavia",
        "2P": "Air Philippines",
        "2Q": "Air Cargo Carriers",
        "2S": "Island Express",
        "2T": "Haiti Ambassador Airlines",
        "2U": "Air Guinee Express",
        "2W": "Welcome Air",
        "2Z": "Changan Airlines",
        "3C": "Air Chathams",
        "3G": "Atlant-Soyuz Airlines",
        "3H": "Air Inuit",
        "3J": "Zip",
        "3K": "Jetstar Asia Airways",
        "3M": "Gulfstream International Airlines",
        "3N": "Air Urga",
        "3P": "Tiara Air",
        "3Q": "Yunnan Airlines",
        "3R": "Moskovia Airlines",
        "3S": "Aeroland Airways",
        "3T": "Turan Air",
        "3U": "Sichuan Airlines",
        "3V": "ASL Airlines Belgium",
        "3W": "Euromanx Airways",
        "4A": "Air Kiribati",
        "4C": "Aires, Aerovias de Integracion Regional, S.A.",
        "4D": "Air Sinai",
        "4F": "Air City",
        "4G": "Gazpromavia",
        "4I": "Knighthawk Air Express",
        "4J": "Somon Air",
        "4K": "Askari Aviation",
        "4L": "Líneas Aéreas Suramericanas",
        "4M": "Aero 2000",
        "4N": "Air North Charter - Canada",
        "4O": "Interjet",
        "4R": "Hamburg International",
        "4S": "Finalair Congo",
        "4T": "Belair Airlines",
        "4U": "Germanwings",
        "4Y": "Airbus France",
        "5A": "Alpine Air Express",
        "5C": "CAL Cargo Air Lines",
        "5D": "Aerolitoral",
        "5D": "DonbassAero",
        "5F": "Arctic Circle Air Service",
        "5G": "Skyservice Airlines",
        "5J": "Cebu Pacific",
        "5K": "Hi Fly",
        "5L": "Aerosur",
        "5M": "Sibaviatrans",
        "5N": "Aeroflot-Nord",
        "5O": "ASL Airlines France",
        "5T": "Canadian North",
        "5V": "Lviv Airlines",
        "5W": "Astraeus",
        "5X": "UPS Airlines",
        "5Y": "Atlas Air",
        "5Z": "Bismillah Airlines",
        "6A": "Consorcio Aviaxsa",
        "6B": "TUI fly Nordic",
        "6E": "IndiGo",
        "6G": "Air Wales",
        "6H": "Israir",
        "6I": "International Business Air",
        "6J": "Solaseed Air",
        "6K": "Asian Spirit",
        "6N": "Nordic Regional",
        "6P": "Club Air",
        "6Q": "Slovak Airlines",
        "6R": "Alrosa Mirny Air Enterprise",
        "6R": "AeroUnion",
        "6U": "Air Ukraine",
        "6V": "Axis Airways",
        "6V": "Mars RK",
        "6V": "Air Vegas",
        "6W": "Saratov Aviation Division",
        "6Z": "Ukrainian Cargo Airways",
        "7B": "Krasnojarsky Airlines",
        "7C": "Jeju Air",
        "7C": "Coyne Airways",
        "7E": "Aeroline GmbH",
        "7F": "First Air",
        "7G": "StarFlyer",
        "7H": "Ravn Alaska",
        "7K": "Kogalymavia Air Company",
        "7L": "Silk Way West Airlines",
        "7M": "Mistral Air",
        "7N": "Centavia",
        "7O": "Galaxy Air",
        "7P": "Metro Batavia",
        "7R": "BRA-Transportes Aereos",
        "7T": "Air Glaciers",
        "7T": "Tobruk Air",
        "7W": "Wayraperú",
        "8A": "Atlas Blue",
        "8B": "Caribbean Star Airlines",
        "8C": "Air Transport International",
        "8D": "Expo Aviation",
        "8E": "Bering Air",
        "8F": "Fischer Air",
        "8H": "Heli France",
        "8J": "Komiinteravia",
        "8L": "Cargo Plus Aviation",
        "8L": "Redhill Aviation",
        "8M": "Maxair",
        "8N": "Barents AirLink",
        "8P": "Pacific Coastal Airline",
        "8Q": "Onur Air",
        "8T": "Air Tindi",
        "8U": "Afriqiyah Airways",
        "8V": "Astral Aviation",
        "8V": "Wright Air Service",
        "8W": "Private Wings Flugcharter",
        "8Y": "Air Burundi",
        "8z": "Linea Aerea de Servicio Ejecutivo Regional",
        "9C": "Spring Airlines",
        "9E": "Endeavor Air",
        "9H": "Dutch Antilles Express",
        "9I": "Alliance Air",
        "9K": "Cape Air",
        "9L": "Colgan Air",
        "9Q": "PB Air",
        "9R": "Phuket Air",
        "9S": "Southern Air",
        "9T": "Transwest Air",
        "9T": "Air ACT",
        "9U": "Air Moldova",
        "9W": "Jet Airways",
        "9X": "Itali Airlines",
        "8R": "RAVSAIR"
    };

    return airlines[IATA] || "Unknown Airline";
};

// airlineIATA koduna göre ülke adının alınması.
export function getCountryNameByIATA(direction, IATA) {
    const countries = {
        "AAR": "Denmark",
        "ABD": "Iran",
        "AEH": "Chad",
        "ABZ": "United Kingdom",
        "LHR": "United Kingdom",
        "LTN": "United Kingdom",
        "LCY": "United Kingdom",
        "LGW": "United Kingdom",
        "ABR": "USA",
        "ABJ": "Cote d'Ivoire",
        "ABI": "USA",
        "AUH": "United Arab Emirates",
        "AUE": "Egypt",
        "ABS": "Egypt",
        "ABV": "Nigeria",
        "ACA": "Mexico",
        "ACC": "Ghana",
        "ADA": "Turkey",
        "ADD": "Ethiopia",
        "ADL": "Australia",
        "ADE": "Yemen",
        "ADF": "Turkey",
        "AER": "Russia",
        "AJY": "Niger",
        "AGA": "Morocco",
        "SUM": "Guam",
        "AGZ": "South Africa",
        "BQN": "Puerto Rico",
        "AGU": "Mexico",
        "AMD": "India",
        "AYU": "Papua New Guinea",
        "AJA": "France",
        "AXT": "Japan",
        "CAK": "USA",
        "AKT": "Cyprus",
        "AAN": "United Arab Emirates",
        "AAC": "Egypt",
        "AHU": "Morocco",
        "ALH": "Australia",
        "ABY": "USA",
        "ALB": "USA",
        "LBI": "France",
        "AAL": "Denmark",
        "ABQ": "USA",
        "ABX": "Australia",
        "ACI": "Channel Islands",
        "ALP": "Syria",
        "AES": "Norway",
        "ALJ": "South Africa",
        "ESF": "USA",
        "HBH": "Egypt",
        "ALY": "Egypt",
        "FJR": "United Arab Emirates",
        "AHO": "Italy",
        "ALG": "Algeria",
        "ALC": "Spain",
        "ASP": "Australia",
        "ADY": "South Africa",
        "ABE": "USA",
        "ALA": "Kazakhstan",
        "LEI": "Spain",
        "ALF": "Norway",
        "AAT": "PR China",
        "ACH": "Switzerland",
        "AOO": "USA",
        "AXS": "USA",
        "ASJ": "Japan",
        "AMA": "USA",
        "AZB": "Papua New Guinea",
        "ADJ": "Jordan",
        "AMM": "Jordan",
        "ATQ": "India",
        "AMS": "Netherlands",
        "QNB": "India",
        "ANC": "USA",
        "AOI": "Italy",
        "ALV": "Andorra",
        "AXA": "Anguilla",
        "AJN": "Comoros",
        "ANK": "Turkey",
        "ESB": "Turkey",
        "ARB": "USA",
        "AAE": "Algeria",
        "NCY": "France",
        "ANB": "USA",
        "AYT": "Turkey",
        "TNR": "Madagascar",
        "ANU": "Antigua and Barbuda",
        "ANR": "Belgium",
        "AOJ": "Japan",
        "APW": "Samoa",
        "ATW": "USA",
        "AQJ": "Jordan",
        "AJU": "Brazil",
        "GPA": "Greece",
        "ARH": "Russia",
        "RLT": "Niger",
        "ACE": "Spain",
        "AUA": "Aruba",
        "ARK": "Tanzania",
        "AVL": "USA",
        "ASB": "Turkmenistan",
        "ASM": "Eritrea",
        "ASE": "USA",
        "ATZ": "Egypt",
        "TSE": "Kazakhstan",
        "ASU": "Paraguay",
        "ASW": "Egypt",
        "AHN": "USA",
        "ATO": "USA",
        "ATH": "Greece",
        "HEW": "Greece",
        "ATL": "USA",
        "ACY": "USA",
        "YAT": "Canada",
        "AKL": "New Zealand",
        "AGB": "Germany",
        "AGS": "USA",
        "AUG": "USA",
        "AUR": "France",
        "AUS": "USA",
        "AYW": "Indonesia",
        "AYQ": "Australia",
        "AYR": "Australia",
        "BJZ": "Spain",
        "BGW": "Iraq",
        "IXB": "India",
        "NAS": "The Bahamas",
        "BHV": "Pakistan",
        "BAH": "Bahrain",
        "BFL": "USA",
        "BAK": "Azerbaijan",
        "BNK": "Australia",
        "BWI": "USA",
        "ABM": "Australia",
        "BKO": "Mali",
        "BBY": "Central African Republic",
        "BWN": "Brunei",
        "BDO": "Indonesia",
        "BLR": "India",
        "BGU": "Central African Republic",
        "DMK": "Thailand",
        "BKK": "Thailand",
        "BGR": "USA",
        "BGF": "Central African Republic",
        "BJL": "Gambia",
        "BNP": "Pakistan",
        "BCN": "Spain",
        "BLA": "Venezuela",
        "BDU": "Norway",
        "BRI": "Italy",
        "BZL": "Bangladesh",
        "BDQ": "India",
        "BRR": "United Kingdom",
        "BAQ": "Colombia",
        "BSL": "Switzerland",
        "EAP": "Switzerland/France",
        "BSR": "Iraq",
        "PTP": "Guadeloupe",
        "SKB": "Saint Kitts and Nevis",
        "BIA": "France",
        "BTR": "USA",
        "BYU": "Germany",
        "BPT": "USA",
        "BKW": "USA",
        "EIS": "Virgin Islands (British)",
        "PEK": "China",
        "NAY": "China",
        "BEW": "Mozambique",
        "BEY": "Lebanon",
        "BEL": "Brazil",
        "BFS": "United Kingdom",
        "BHD": "United Kingdom",
        "IXG": "India",
        "BEG": "Serbia",
        "BZE": "Belize",
        "BLI": "USA",
        "CNF": "Brazil",
        "BJI": "USA",
        "BEB": "United Kingdom",
        "BEN": "Libya",
        "BUG": "Angola",
        "BEH": "USA",
        "BBT": "Central African Republic",
        "BGY": "Italy",
        "BGO": "Norway",
        "EGC": "France",
        "BER": "Germany",
        "SXF": "Germany",
        "TXL": "Germany",
        "THF": "Germany",
        "BDA": "Bermuda",
        "BRN": "Switzerland",
        "ZDJ": "Switzerland",
        "BET": "USA",
        "BHO": "India",
        "BBI": "India",
        "BIQ": "France",
        "BIO": "Spain",
        "BIL": "USA",
        "BLL": "Denmark",
        "BTU": "Malaysia",
        "IRO": "Central African Republic",
        "BHM": "USA",
        "BHX": "United Kingdom",
        "FRU": "Kyrgyzstan",
        "BIS": "USA",
        "BXO": "Guinea-Bissau",
        "BLK": "United Kingdom",
        "BLT": "Australia",
        "BLZ": "Malawi",
        "BHE": "New Zealand",
        "BFN": "South Africa",
        "BMI": "USA",
        "BMG": "USA",
        "BLF": "USA",
        "BVB": "Brazil",
        "BOY": "Burkina Faso",
        "BOO": "Norway",
        "BJV": "Turkey",
        "BOG": "Colombia",
        "BOI": "USA",
        "BLQ": "Italy",
        "BOM": "India",
        "BON": "Netherlands Antilles",
        "YVB": "Canada",
        "BOB": "French Polynesia",
        "BOD": "France",
        "BXS": "USA",
        "BOS": "USA",
        "BYK": "Cote d'Ivoire",
        "BOJ": "Bulgaria",
        "BOH": "United Kingdom",
        "ZBO": "Australia",
        "BZN": "USA",
        "BFD": "USA",
        "BRD": "USA",
        "BMP": "Australia",
        "BSB": "Brazil",
        "BTS": "Slovakia",
        "BZV": "Congo (ROC)",
        "BRE": "Germany",
        "VBS": "Italy",
        "BES": "France",
        "BIV": "Central African Republic",
        "BDR": "USA",
        "BGI": "Barbados",
        "BDS": "Italy",
        "BNE": "Australia",
        "BRS": "United Kingdom",
        "BNN": "Norway",
        "BHQ": "Australia",
        "BKX": "USA",
        "BME": "Australia",
        "BQK": "USA",
        "BRU": "Belgium",
        "BGA": "Colombia",
        "BUH": "Romania",
        "OTP": "Romania",
        "BUD": "Hungary",
        "BUE": "Argentina",
        "EZE": "Argentina",
        "AEP": "Argentina",
        "BFO": "Zimbabwe",
        "BUF": "USA",
        "BJM": "Burundi",
        "BUQ": "Zimbabwe",
        "BHC": "USA",
        "BDB": "Australia",
        "BUR": "USA",
        "BTV": "USA",
        "BRL": "USA",
        "BWT": "Australia",
        "BTM": "USA",
        "CAB": "Angola",
        "CAG": "Italy",
        "CNS": "Australia",
        "CAI": "Egypt",
        "CJC": "Chile",
        "CCU": "India",
        "YYC": "Canada",
        "CLO": "Colombia",
        "CCJ": "India",
        "CLY": "France",
        "YCB": "Canada",
        "CBG": "United Kingdom",
        "CAL": "United Kingdom",
        "CGR": "Brazil",
        "CBR": "Australia",
        "CUN": "Mexico",
        "CEQ": "France",
        "CIW": "Saint Vincent & the Grenadines",
        "CPT": "South Africa",
        "CCS": "Venezuela",
        "CWL": "United Kingdom",
        "CLD": "USA",
        "CVQ": "Australia",
        "CRF": "Central African Republic",
        "CSN": "USA",
        "CTG": "Colombia",
        "LRM": "Dominican Republic",
        "CAS": "Morocco",
        "CMN": "Morocco",
        "CSI": "Australia",
        "CPR": "USA",
        "CST": "Fiji",
        "SLU": "Saint Lucia",
        "CTA": "Italy",
        "CAY": "French Guiana",
        "CEB": "Philippines",
        "CDC": "USA",
        "CID": "USA",
        "CED": "Australia",
        "CES": "Australia",
        "KHV": "Russia",
        "CMF": "France",
        "CMI": "USA",
        "IXC": "India",
        "CGQ": "PR China",
        "CHQ": "Greece",
        "CHG": "PR China",
        "CHS": "USA",
        "CRW": "USA",
        "CLT": "USA",
        "CHO": "USA",
        "CXT": "Australia",
        "CHA": "USA",
        "CTU": "PR China",
        "MAA": "India",
        "CYS": "USA",
        "CNX": "Thailand",
        "QCB": "Japan",
        "CHI": "USA",
        "MDW": "USA",
        "ORD": "USA",
        "CZA": "Mexico",
        "CIC": "USA",
        "CUU": "Mexico",
        "JKH": "Greece",
        "CIP": "Zambia",
        "KIV": "Moldova",
        "HTA": "Russia",
        "CJL": "Pakistan",
        "CGP": "Bangladesh",
        "CKG": "PR China",
        "CHC": "New Zealand",
        "CCZ": "Bahamas",
        "YYQ": "Canada",
        "CFG": "Cuba",
        "CVG": "USA",
        "CME": "Mexico",
        "CGU": "Venezuela",
        "CJS": "Mexico",
        "CEN": "Mexico",
        "CVM": "Mexico",
        "CKB": "USA",
        "CMQ": "Australia",
        "CFE": "France",
        "CLE": "USA",
        "BKL": "USA",
        "CBB": "Bolivia",
        "COK": "India",
        "COD": "USA",
        "KCC": "USA",
        "CFS": "Australia",
        "CJB": "India",
        "CLQ": "Mexico",
        "CLL": "USA",
        "KCE": "Australia",
        "CGN": "Germany",
        "CMB": "Sri Lanka",
        "COS": "USA",
        "CAE": "USA",
        "CSG": "USA",
        "CMH": "USA",
        "CKY": "Guinea",
        "CCR": "USA",
        "CON": "USA",
        "CND": "Romania",
        "CZL": "Algeria",
        "CPD": "Australia",
        "CTN": "Australia",
        "OOM": "Australia",
        "CPH": "Denmark",
        "COR": "Argentina",
        "ODB": "Spain",
        "CDV": "USA",
        "CFU": "Greece",
        "ORK": "Ireland",
        "CRP": "USA",
        "COO": "Benin",
        "CBU": "Germany",
        "CVT": "United Kingdom",
        "CZM": "Mexico",
        "CGA": "USA",
        "CEC": "USA",
        "CGB": "Brazil",
        "CUL": "Mexico",
        "CUR": "Netherlands Antilles",
        "CWB": "Brazil",
        "CYU": "Philippines",
        "DKR": "Senegal",
        "DLM": "Turkey",
        "DBY": "Australia",
        "DLC": "PR China",
        "DAL": "USA",
        "DFW": "USA",
        "DJO": "Cote d'Ivoire",
        "DAM": "Syria",
        "DMM": "Saudi Arabia",
        "DAN": "USA",
        "DAR": "Tanzania",
        "DRW": "Australia",
        "DDI": "Australia",
        "DAY": "USA",
        "DAB": "USA",
        "DEC": "USA",
        "YDF": "Canada",
        "DEL": "India",
        "HAG": "Netherlands",
        "DNZ": "Turkey",
        "DPS": "Indonesia",
        "DEN": "USA",
        "DSK": "Pakistan",
        "DRB": "Australia",
        "LDY": "United Kingdom",
        "DSM": "USA",
        "DET": "USA",
        "DTT": "USA",
        "DTW": "USA",
        "DVL": "USA",
        "DPO": "Australia",
        "DHA": "Saudi Arabia",
        "DAC": "Bangladesh",
        "DIL": "Timor Leste",
        "DLG": "USA",
        "DNR": "France",
        "DLP": "France",
        "DJE": "Tunisia",
        "JIB": "Djibouti",
        "DOD": "Tanzania",
        "DOH": "Qatar",
        "DSA": "United Kingdom",
        "CFN": "Ireland",
        "DTM": "Germany",
        "DHN": "USA",
        "DLA": "Cameroon",
        "DRS": "Germany",
        "DXB": "United Arab Emirates",
        "DBO": "Australia",
        "DUB": "Ireland",
        "DUJ": "USA",
        "DBV": "Croatia",
        "DBQ": "USA",
        "DUS": "Germany",
        "DLH": "USA",
        "DND": "United Kingdom",
        "DUD": "New Zealand",
        "DKI": "Australia",
        "DRO": "USA",
        "DUR": "South Africa",
        "DYU": "Tajikistan",
        "DUT": "USA",
        "DYA": "Australia",
        "DZA": "Mayotte",
        "ELS": "South Africa",
        "IPC": "Chile",
        "EAU": "USA",
        "EDI": "Scotland",
        "YEA": "Canada",
        "YEG": "Canada",
        "YXD": "Canada",
        "EGS": "Iceland",
        "EIN": "Netherlands",
        "EMY": "Egypt",
        "ELP": "USA",
        "ETH": "Israel",
        "VDA": "Israel",
        "EBA": "Italy",
        "EKI": "USA",
        "EKO": "USA",
        "ELL": "South Africa",
        "ELM": "USA",
        "ELY": "USA",
        "EDR": "Australia",
        "EMD": "Australia",
        "ENF": "Finland",
        "EBB": "Uganda",
        "ERF": "Germany",
        "ERI": "USA",
        "EVN": "Armenia",
        "ERC": "Turkey",
        "ERZ": "Turkey",
        "EBJ": "Denmark",
        "ESC": "USA",
        "EPR": "Australia",
        "EUG": "USA",
        "ACV": "USA",
        "EVV": "USA",
        "EVE": "Norway",
        "EXT": "United Kingdom",
        "FIE": "United Kingdom",
        "FAI": "USA",
        "LYP": "Pakistan",
        "FAR": "USA",
        "FMN": "USA",
        "FAO": "Portugal",
        "FAE": "Denmark",
        "FYV": "USA",
        "FAY": "USA",
        "FEZ": "Morocco",
        "FSC": "France",
        "FLG": "USA",
        "YFO": "Canada",
        "FNT": "USA",
        "FLO": "USA",
        "FLR": "Italy",
        "FLN": "Brazil",
        "FRO": "Norway",
        "YFA": "Canada",
        "FDF": "Martinique",
        "FOD": "USA",
        "FHU": "USA",
        "FLL": "USA",
        "YMM": "Canada",
        "FMY": "USA",
        "RSW": "USA",
        "FRI": "USA",
        "YSM": "Canada",
        "FSM": "USA",
        "YXJ": "Canada",
        "VPS": "USA",
        "FWA": "USA",
        "DFW": "USA",
        "FOR": "Brazil",
        "FOU": "United Kingdom",
        "FRW": "Botswana",
        "HHN": "Germany",
        "FRA": "Germany",
        "FKL": "USA",
        "YFC": "Canada",
        "FPO": "Bahamas",
        "FNA": "Sierra Leone",
        "FRJ": "France",
        "FAT": "USA",
        "FDH": "Germany",
        "FUE": "Spain",
        "FJR": "United Arab Emirates",
        "FUK": "Japan",
        "FKS": "Japan",
        "FNC": "Portugal",
        "FUT": "Wallis and Futuna Islands",
        "GBE": "Botswana",
        "GAD": "USA",
        "GNV": "USA",
        "GWY": "Ireland",
        "YQX": "Canada",
        "GOU": "Cameroon",
        "GZA": "Palestinian Territory",
        "GZT": "Turkey",
        "GDN": "Poland",
        "GEX": "Australia",
        "GVA": "Switzerland",
        "GOA": "Italy",
        "GRJ": "South Africa",
        "GEO": "Guyana",
        "GET": "Australia",
        "GRO": "Spain",
        "GNE": "Belgium",
        "GIB": "Gibraltar",
        "GCC": "USA",
        "GIL": "Pakistan",
        "YGX": "Canada",
        "GLT": "Australia",
        "GLA": "United Kingdom",
        "GGW": "USA",
        "PIK": "United Kingdom",
        "GDV": "USA",
        "GOI": "India",
        "GYN": "Brazil",
        "OOL": "Australia",
        "GOO": "Australia",
        "YYR": "Canada",
        "GOZ": "Bulgaria",
        "GOT": "Sweden",
        "GOV": "Australia",
        "GHB": "Bahamas",
        "GRX": "Spain",
        "FPO": "Bahamas",
        "GCN": "USA",
        "GCM": "Cayman Islands",
        "GFK": "USA",
        "GJT": "USA",
        "GRR": "USA",
        "GPZ": "USA",
        "GRZ": "Austria",
        "GTF": "USA",
        "GKL": "Australia",
        "GRB": "USA",
        "LWB": "USA",
        "GSO": "USA",
        "GLH": "USA",
        "PGV": "USA",
        "GSP": "USA",
        "GND": "Grenada",
        "GNB": "France",
        "GFF": "Australia",
        "GRQ": "Netherlands",
        "GTE": "Australia",
        "GON": "USA",
        "GDL": "Mexico",
        "GSI": "Solomon Islands",
        "GUM": "Guam",
        "CAN": "PR China",
        "GUA": "Guatemala",
        "GYE": "Ecuador",
        "GCI": "Channel Islands",
        "GTI": "Germany",
        "KWL": "PR China",
        "GPT": "USA",
        "ULU": "Uganda",
        "GUC": "USA",
        "GAU": "India",
        "GWD": "Pakistan",
        "GWE": "Zimbabwe",
        "GYP": "Australia",
        "HAC": "Japan",
        "GUM": "Guam",
        "HFA": "Israel",
        "HNS": "USA",
        "HKD": "Japan",
        "YHZ": "Canada",
        "YUX": "Canada",
        "HAM": "Germany",
        "HLT": "Australia",
        "HLZ": "New Zealand",
        "YHM": "Canada",
        "HTI": "Australia",
        "HFT": "Norway",
        "CMX": "USA",
        "HGH": "PR China",
        "HAJ": "Germany",
        "HAN": "Vietnam",
        "HRE": "Zimbabwe",
        "HRB": "PR China",
        "HRL": "USA",
        "YHR": "Canada",
        "MDT": "USA",
        "HAR": "USA",
        "BDL": "USA",
        "HDY": "Thailand",
        "HAU": "Norway",
        "HAV": "Cuba",
        "HVR": "USA",
        "HIS": "Australia",
        "HLN": "USA",
        "JHE": "Sweden",
        "HEL": "Finland",
        "HER": "Greece",
        "HMO": "Mexico",
        "HVB": "Australia",
        "HIB": "USA",
        "HKY": "USA",
        "ITO": "USA",
        "HHH": "USA",
        "HNK": "Australia",
        "HIJ": "Japan",
        "SGN": "Vietnam",
        "HBA": "Australia",
        "HOQ": "Germany",
        "HOG": "Cuba",
        "HMH": "Australia",
        "HOM": "USA",
        "ZJK": "Hong Kong",
        "HKG": "Hong Kong",
        "HIR": "Solomon Islands",
        "HNL": "USA",
        "HNH": "USA",
        "HOR": "Portugal",
        "HOU": "USA",
        "IAH": "USA",
        "HUH": "French Polynesia",
        "HUX": "Mexico",
        "HUI": "Vietnam",
        "HUY": "United Kingdom",
        "HTS": "USA",
        "HSV": "USA",
        "HRG": "Egypt",
        "HON": "USA",
        "HWN": "Zimbabwe",
        "HYA": "USA",
        "HYG": "USA",
        "HDD": "Pakistan",
        "HYD": "India",
        "IBZ": "Spain",
        "IDA": "USA",
        "IGR": "Argentina",
        "ILP": "New Caledonia",
        "IOU": "New Caledonia",
        "ILI": "USA",
        "IPL": "USA",
        "IVC": "New Zealand",
        "ICN": "Korea South",
        "IND": "USA",
        "IGH": "Australia",
        "IFL": "Australia",
        "INN": "Austria",
        "INL": "USA",
        "YEV": "Canada",
        "INV": "United Kingdom",
        "IYK": "USA",
        "YFB": "Canada",
        "IQT": "Peru",
        "IKT": "Russia",
        "ISG": "Japan",
        "ISB": "Pakistan",
        "ILY": "United Kingdom",
        "IOM": "Isle of Man",
        "IST": "Turkey",
        "SAW": "Turkey",
        "ITH": "USA",
        "IVL": "Finland",
        "ZIH": "Mexico",
        "IZM": "Turkey",
        "ADB": "Turkey",
        "JXN": "USA",
        "MKL": "USA",
        "JAC": "USA",
        "HKS": "USA",
        "JAN": "USA",
        "MJQ": "USA",
        "LRF": "USA",
        "IJX": "USA",
        "OAJ": "USA",
        "JKV": "USA",
        "NZC": "USA",
        "CRG": "USA",
        "JAX": "USA",
        "NIP": "USA",
        "JAK": "Haiti",
        "JAG": "Pakistan",
        "JCM": "Brazil",
        "JAQ": "Papua New Guinea",
        "JAF": "Sri Lanka",
        "JGB": "India",
        "JAI": "India",
        "JSA": "India",
        "HLP": "Indonesia",
        "JKT": "Indonesia",
        "CGK": "Indonesia",
        "JAA": "Afghanistan",
        "JLR": "India",
        "JAL": "Mexico",
        "JLS": "Brazil",
        "UIT": "Marshall Islands",
        "JMB": "Angola",
        "DJB": "Indonesia",
        "JAM": "Bulgaria",
        "JMS": "USA",
        "JHW": "USA",
        "IXJ": "India",
        "JGA": "India",
        "IXW": "India",
        "JKR": "Nepal",
        "JAD": "Australia",
        "JVL": "USA",
        "JNA": "Brazil",
        "JQE": "Panama",
        "JTI": "Brazil",
        "JAU": "Peru",
        "DJJ": "Indonesia",
        "JED": "Saudi Arabia",
        "JEF": "USA",
        "JEE": "Haiti",
        "XRY": "Spain",
        "JER": "Channel Islands",
        "JRS": "Israel",
        "JSR": "Bangladesh",
        "PYB": "India",
        "JMU": "PR China",
        "JGS": "China",
        "JGN": "PR China",
        "GJL": "Algeria",
        "JIJ": "Ethiopia",
        "JIL": "PR China",
        "JIM": "Ethiopia",
        "TNA": "PR China",
        "JDZ": "PR China",
        "JHG": "PR China",
        "JNG": "PR China",
        "JIN": "Uganda",
        "JJN": "PR China",
        "BCO": "Ethiopia",
        "JNZ": "PR China",
        "JIP": "Ecuador",
        "JIR": "Nepal",
        "JIU": "PR China",
        "JIW": "Pakistan",
        "JCB": "Brazil",
        "JPA": "Brazil",
        "JDH": "India",
        "JOE": "Finland",
        "JNB": "South Africa",
        "BGM": "USA",
        "JON": "USA",
        "JST": "USA",
        "JHB": "Malaysia",
        "JOI": "Brazil",
        "JOL": "Philippines",
        "JMO": "Nepal",
        "JBR": "USA",
        "JKG": "Sweden",
        "JLN": "USA",
        "JRH": "India",
        "JOS": "Nigeria",
        "JSM": "Argentina",
        "AJF": "Saudi Arabia",
        "JJI": "Peru",
        "JUB": "South Sudan",
        "JUI": "Germany",
        "JDF": "Brazil",
        "JUJ": "Argentina",
        "JCK": "Australia",
        "JUL": "Peru",
        "JUM": "Nepal",
        "JUN": "Australia",
        "JNU": "USA",
        "JNI": "Argentina",
        "JUT": "Honduras",
        "JWA": "Botswana",
        "JYV": "Finland",
        "KBL": "Afghanistan",
        "KOJ": "Japan",
        "KCM": "Turkey",
        "OGG": "USA",
        "KAJ": "Finland",
        "KLX": "Greece",
        "AZO": "USA",
        "KGI": "Australia",
        "KGD": "Russia",
        "FCA": "USA",
        "KLR": "Sweden",
        "YKA": "Canada",
        "MUE": "USA",
        "KAN": "Nigeria",
        "KNU": "India",
        "MCI": "USA",
        "KHH": "Taiwan",
        "JHM": "USA",
        "KHI": "Pakistan",
        "FKB": "Germany",
        "KSD": "Sweden",
        "AOK": "Greece",
        "KTA": "Australia",
        "KYS": "Turkey",
        "KRB": "Australia",
        "KRP": "Denmark",
        "ZKE": "Canada",
        "KSL": "Sudan",
        "KTR": "Australia",
        "KTM": "Nepal",
        "MPA": "Namibia",
        "KHJ": "Finland",
        "MKK": "USA",
        "KVA": "Greece",
        "ASR": "Turkey",
        "KZN": "Russia",
        "KMP": "Namibia",
        "YLW": "Canada",
        "KEM": "Finland",
        "ENA": "USA",
        "MSE": "United Kingdom",
        "KIR": "Ireland",
        "KTN": "USA",
        "EYW": "USA",
        "AHB": "Saudi Arabia",
        "UVL": "Egypt",
        "HRK": "Ukraine",
        "KRT": "Sudan",
        "KDD": "Pakistan",
        "KEL": "Germany",
        "KBP": "Ukraine",
        "IEV": "Ukraine",
        "KGL": "Rwanda",
        "JRO": "Tanzania",
        "ILE": "USA",
        "KIM": "South Africa",
        "KNS": "Australia",
        "AKN": "USA",
        "KGC": "Australia",
        "ISO": "USA",
        "KIN": "Jamaica",
        "SVD": "Saint Vincent and the Grenadines",
        "FIH": "Congo (DRC)",
        "CXI": "Kiribati",
        "KKN": "Norway",
        "KIK": "Iraq",
        "KOI": "United Kingdom",
        "KRN": "Sweden",
        "FKI": "Congo (DRC)",
        "KTT": "Finland",
        "KIW": "Zambia",
        "KLU": "Austria",
        "LMT": "USA",
        "KLW": "USA",
        "KLZ": "South Africa",
        "NOC": "Ireland",
        "TYS": "USA",
        "UKB": "Japan",
        "KCZ": "Japan",
        "ADQ": "USA",
        "OHT": "Pakistan",
        "KOK": "Finland",
        "CCU": "India",
        "CGN": "Germany",
        "KMQ": "Japan",
        "KOA": "USA",
        "KYA": "Turkey",
        "HGO": "Cote d'Ivoire",
        "KGS": "Greece",
        "BKI": "Malaysia",
        "OTZ": "USA",
        "KWM": "Australia",
        "KRK": "Poland",
        "KRS": "Norway",
        "KID": "Sweden",
        "KSU": "Norway",
        "KUL": "Malaysia",
        "SZB": "Malaysia",
        "KUA": "Malaysia",
        "KCH": "Malaysia",
        "KMJ": "Japan",
        "KNX": "Australia",
        "KUO": "Finland",
        "KUH": "Japan",
        "YVP": "Canada",
        "YGW": "Canada",
        "KAO": "Finland",
        "KWI": "Kuwait",
        "UKY": "Japan",
        "LCG": "Spain",
        "LSE": "USA",
        "YGL": "Canada",
        "LAP": "Mexico",
        "LPB": "Bolivia",
        "LRH": "France",
        "LEK": "Guinea",
        "WLB": "USA",
        "LBU": "Malaysia",
        "XLB": "Canada",
        "LAE": "Papua New Guinea",
        "LAF": "USA",
        "LFT": "USA",
        "LOS": "Nigeria",
        "LHE": "Pakistan",
        "LCH": "USA",
        "HII": "USA",
        "TVL": "USA",
        "LKL": "Norway",
        "LBQ": "Gabon",
        "SUF": "Italy",
        "LMP": "Italy",
        "LNY": "USA",
        "LNS": "USA",
        "LEQ": "United Kingdom",
        "LGK": "Malaysia",
        "LAI": "France",
        "HLA": "South Africa",
        "LAN": "USA",
        "LPP": "Finland",
        "LAR": "USA",
        "LRD": "USA",
        "LCA": "Cyprus",
        "LPA": "Spain",
        "LAS": "USA",
        "LBE": "USA",
        "LST": "Australia",
        "PIB": "USA",
        "LVO": "Australia",
        "LAW": "USA",
        "LZC": "Mexico",
        "YLR": "Canada",
        "LEA": "Australia",
        "LEB": "USA",
        "LBA": "United Kingdom",
        "LER": "Australia",
        "LEJ": "Germany",
        "LEY": "Netherlands",
        "BJX": "Mexico",
        "LNO": "Australia",
        "LWK": "United Kingdom",
        "LWS": "USA",
        "LWT": "USA",
        "LEX": "USA",
        "LBV": "Gabon",
        "LDK": "Sweden",
        "LGG": "Belgium",
        "LIF": "Loyaute, Pazifik",
        "LIH": "USA",
        "LIL": "France",
        "LLW": "Malawi",
        "LIM": "Peru",
        "QLI": "Cyprus",
        "LIG": "France",
        "LNK": "USA",
        "LDC": "Australia",
        "LIS": "Portugal",
        "LSZ": "Croatia",
        "SDF": "USA",
        "LDE": "France",
        "LAD": "Angola",
        "LBB": "USA",
        "LKO": "India",
        "LUD": "Namibia",
        "MLA": "Malta",
        "LUG": "Switzerland",
        "LLA": "Sweden",
        "FBM": "Congo (DRC)",
        "LUN": "Zambia",
        "LUJ": "South Africa",
        "LUX": "Luxembourg",
        "LUM": "PR China",
        "LXR": "Egypt",
        "LWO": "Ukraine",
        "LYX": "United Kingdom",
        "LYH": "USA",
        "LYS": "France",
        "LYO": "USA",
        "MST": "Netherlands",
        "MCP": "Brazil",
        "MFM": "Macau, China SAR",
        "MCZ": "Brazil",
        "MKY": "Australia",
        "MCN": "USA",
        "NOP": "Philippines",
        "MED": "Saudi Arabia",
        "MSN": "USA",
        "MAA": "India",
        "MAD": "Spain",
        "SEZ": "Seychelles",
        "MAH": "Spain",
        "MTL": "Australia",
        "MJN": "Madagascar",
        "MZG": "Taiwan",
        "SSG": "Equatorial Guinea",
        "AGP": "Spain",
        "MLX": "Turkey",
        "MLE": "Maldives",
        "MYD": "Kenya",
        "MMX": "Sweden",
        "MMA": "Sweden",
        "MJC": "Cote d'Ivoire",
        "MDC": "Indonesia",
        "MGA": "Nicaragua",
        "MAO": "Brazil",
        "MAN": "United Kingdom",
        "MHT": "USA",
        "MDL": "Myanmar",
        "MFO": "Papua New Guinea",
        "XMH": "French Polynesia",
        "MNL": "Philippines",
        "ZLO": "Mexico",
        "MTS": "Swaziland",
        "MPM": "Mozambique",
        "MDQ": "Argentina",
        "MAR": "Venezuela",
        "MFQ": "Niger",
        "KCM": "Turkey",
        "MTH": "USA",
        "MQM": "Turkey",
        "MEE": "New Caledonia",
        "MGH": "South Africa",
        "PMV": "Venezuela",
        "MBX": "Slovenia",
        "MHQ": "Finland",
        "MVR": "Cameroon",
        "MQT": "USA",
        "RAK": "Morocco",
        "RMF": "Egypt",
        "MUH": "Egypt",
        "MRS": "France",
        "MHH": "Bahamas",
        "MVY": "USA",
        "MRB": "USA",
        "MBH": "Australia",
        "MSU": "Lesotho",
        "MCW": "USA",
        "MVZ": "Zimbabwe",
        "MMJ": "Japan",
        "MYJ": "Japan",
        "MTO": "USA",
        "MUB": "Botswana",
        "MAU": "French Polynesia",
        "MRU": "Mauritius",
        "MAZ": "Puerto Rico",
        "MZT": "Mexico",
        "MFE": "USA",
        "KNO": "Indonesia",
        "MES": "Indonesia",
        "MDE": "Colombia",
        "MFR": "USA",
        "MED": "Saudi Arabia",
        "MKR": "Australia",
        "MLB": "USA",
        "MEL": "Australia",
        "DOM": "Dominica",
        "MEM": "USA",
        "MDZ": "Argentina",
        "MCE": "USA",
        "MID": "Mexico",
        "MEI": "USA",
        "MIM": "Australia",
        "MEZ": "South Africa",
        "MTM": "USA",
        "MZM": "France",
        "ETZ": "France",
        "MXL": "Mexico",
        "AZP": "Mexico",
        "MEX": "Mexico",
        "NLU": "Mexico",
        "MFU": "Zambia",
        "MIA": "USA",
        "MWD": "Pakistan",
        "MMM": "Australia",
        "MAF": "USA",
        "MDY": "US Minor Outlying Islands",
        "MIK": "Finland",
        "MIL": "Italy",
        "LIN": "Italy",
        "MXP": "Italy",
        "BGY": "Italy",
        "MQL": "Australia",
        "MLS": "USA",
        "MFN": "New Zealand",
        "MKE": "USA",
        "MTT": "Mexico",
        "MRV": "Russia",
        "MSP": "USA",
        "MOT": "USA",
        "MSQ": "Belarus",
        "MYY": "Malaysia",
        "QML": "Pakistan",
        "MSO": "USA",
        "MHE": "USA",
        "MMY": "Japan",
        "KMI": "Japan",
        "MBM": "South Africa",
        "MFF": "Gabon",
        "MOB": "USA",
        "MOD": "USA",
        "MJD": "Pakistan",
        "MGQ": "Somalia",
        "OKU": "Namibia",
        "MLI": "USA",
        "MBA": "Kenya",
        "MIR": "Tunisia",
        "YQM": "Canada",
        "MLW": "Liberia",
        "ROB": "Liberia",
        "MBJ": "Jamaica",
        "QGF": "Brazil",
        "MRY": "USA",
        "NTR": "Mexico",
        "MTY": "Mexico",
        "MVD": "Uruguay",
        "MGM": "USA",
        "MPL": "France",
        "YMQ": "Canada",
        "YUL": "Canada",
        "YMX": "Canada",
        "MTJ": "USA",
        "MOZ": "French Polynesia",
        "MOV": "Australia",
        "MRZ": "Australia",
        "MLM": "Mexico",
        "MGW": "USA",
        "HNA": "Japan",
        "HAH": "Comoros",
        "MYA": "Australia",
        "DME": "Russia",
        "MOW": "Russia",
        "SVO": "Russia",
        "VKO": "Russia",
        "MWH": "USA",
        "MZY": "South Africa",
        "OMO": "Bosnia and Herzegovina",
        "OSM": "Iraq",
        "MJL": "Gabon",
        "MQQ": "Chad",
        "GTN": "New Zealand",
        "MGB": "Australia",
        "MMG": "Australia",
        "ISA": "Australia",
        "MCL": "USA",
        "MUC": "Germany",
        "FMO": "Germany",
        "MLH": "France",
        "MUX": "Pakistan",
        "MJV": "Spain",
        "MMK": "Russia",
        "MSR": "Turkey",
        "MCT": "Oman",
        "MSL": "USA",
        "MKG": "USA",
        "MFG": "Pakistan",
        "MVB": "Gabon",
        "JMK": "Greece",
        "CRE": "USA",
        "MYR": "USA",
        "MYQ": "India",
        "MJT": "Greece",
        "MZF": "South Africa",
        "NAN": "Fiji",
        "NGS": "Japan",
        "NGO": "Japan",
        "NAG": "India",
        "NBO": "Kenya",
        "NAJ": "Azerbaijan",
        "NST": "Thailand",
        "ENC": "France",
        "YSR": "Canada",
        "NNG": "China",
        "NTE": "France",
        "ACK": "USA",
        "APF": "USA",
        "NAP": "Italy",
        "NAA": "Australia",
        "NRA": "Australia",
        "UAK": "Greenland",
        "BNA": "USA",
        "NAS": "Bahamas",
        "NAT": "Brazil",
        "SUV": "Fiji",
        "WNS": "Pakistan",
        "JNX": "Greece",
        "NDJ": "Chad",
        "NLA": "Zambia",
        "NSN": "New Zealand",
        "NLP": "South Africa",
        "MQP": "South Africa",
        "NEV": "St. Kitts and Nevis",
        "EWN": "USA",
        "HVN": "USA",
        "MSY": "USA",
        "UVL": "Egypt",
        "JFK": "USA",
        "LGA": "USA",
        "EWR": "USA",
        "NYC": "USA",
        "SWF": "USA",
        "NCL": "United Kingdom",
        "NCS": "South Africa",
        "BEO": "Australia",
        "NTL": "Australia",
        "ZNE": "Australia",
        "PHF": "USA",
        "NQY": "United Kingdom",
        "NGE": "Cameroon",
        "IAG": "USA",
        "NIM": "Niger",
        "NCE": "France",
        "NIC": "Cyprus",
        "KIJ": "Japan",
        "NLV": "Ukraine",
        "FNI": "France",
        "INI": "Serbia",
        "GOJ": "Russia",
        "OME": "USA",
        "NSA": "Australia",
        "NLK": "Australia",
        "ORF": "USA",
        "YVQ": "Canada",
        "NRK": "Sweden",
        "OTH": "USA",
        "ELH": "Bahamas",
        "NWI": "United Kingdom",
        "EMA": "United Kingdom",
        "NDB": "Mauritania",
        "NKC": "Mauritania",
        "NOU": "New Caledonia",
        "QND": "Serbia",
        "OVB": "Russia",
        "NLD": "Mexico",
        "TBU": "Tonga",
        "NUE": "Germany",
        "OAK": "USA",
        "OAX": "Mexico",
        "ODE": "Denmark",
        "ODS": "Ukraine",
        "ORB": "Sweden",
        "OHD": "Macedonia",
        "OIT": "Japan",
        "OKJ": "Japan",
        "OKA": "Japan",
        "OKC": "USA",
        "OLB": "Italy",
        "OLP": "Australia",
        "OMA": "USA",
        "OND": "Namibia",
        "ONT": "USA",
        "ORN": "Algeria",
        "OAG": "Australia",
        "SNA": "USA",
        "OMD": "Namibia",
        "AUA": "Aruba",
        "KOI": "United Kingdom",
        "MCO": "USA",
        "ORL": "USA",
        "ORS": "Australia",
        "ITM": "Japan",
        "KIX": "Japan",
        "OSA": "Japan",
        "OSH": "USA",
        "OSI": "Croatia",
        "FBU": "Norway",
        "OSL": "Norway",
        "TRF": "Norway",
        "YOW": "Canada",
        "ODA": "Central African Republic",
        "OUA": "Burkina Faso",
        "OZZ": "Morocco",
        "OUH": "South Africa",
        "OUD": "Morocco",
        "OUL": "Finland",
        "OUK": "United Kingdom",
        "OVD": "Spain",
        "OWB": "USA",
        "OXR": "USA",
        "UVE": "Gabon/Loyautte",
        "PAD": "Germany",
        "PAH": "USA",
        "PGA": "USA",
        "PPG": "American Samoa",
        "PKB": "USA",
        "PMO": "Italy",
        "PSP": "USA",
        "PMI": "Spain",
        "PMW": "Brazil",
        "PMD": "USA",
        "PMR": "New Zealand",
        "PFN": "USA",
        "PTY": "Panama",
        "PJG": "Pakistan",
        "PNL": "Italy",
        "PPT": "French Polynesia (Tahiti)",
        "PFO": "Cyprus",
        "PBO": "Australia",
        "PBM": "Suriname",
        "PAR": "France",
        "CDG": "France",
        "LBG": "France",
        "ORY": "France",
        "PBH": "Bhutan",
        "PSC": "USA",
        "PSI": "Pakistan",
        "PAT": "India",
        "PYX": "Thailand",
        "PUF": "France",
        "PLN": "USA",
        "PEN": "Malaysia",
        "PDT": "USA",
        "PNS": "USA",
        "PIA": "USA",
        "PEI": "Colombia",
        "PGF": "France",
        "PER": "Australia",
        "PEG": "Italy",
        "PSR": "Italy",
        "PEW": "Pakistan",
        "PSG": "USA",
        "PHW": "South Africa",
        "PHL": "USA",
        "PNH": "Cambodia",
        "PHX": "USA",
        "HKT": "Thailand",
        "PIR": "USA",
        "PZB": "South Africa",
        "PTG": "South Africa",
        "NTY": "South Africa",
        "PSA": "Italy",
        "PIT": "USA",
        "PLB": "USA",
        "PBZ": "South Africa",
        "PIH": "USA",
        "TGD": "Montenegro",
        "PNI": "Micronesia",
        "PTP": "Guadeloupe",
        "PNR": "Congo (ROC)",
        "PIS": "France",
        "PSE": "Puerto Rico",
        "PDL": "Portugal",
        "POR": "Finland",
        "CLM": "USA",
        "PAP": "Haiti",
        "PUG": "Australia",
        "PLZ": "South Africa",
        "POG": "Gabon",
        "PHC": "Nigeria",
        "PHE": "Australia",
        "PLO": "Australia",
        "PQQ": "Australia",
        "YPN": "Canada",
        "POM": "Papua New Guinea",
        "POS": "Trinidad and Tobago",
        "PSD": "Egypt",
        "VLI": "Vanuatu",
        "PTJ": "Australia",
        "PWM": "USA",
        "PDX": "USA",
        "OPO": "Portugal",
        "POA": "Brazil",
        "PXO": "Portugal",
        "PVH": "Brazil",
        "POU": "USA",
        "POZ": "Poland",
        "PRG": "Czech Republic",
        "RAI": "Cape Verde",
        "PQI": "USA",
        "PRY": "South Africa",
        "PVK": "Greece",
        "YXS": "Canada",
        "YPR": "Canada",
        "PRN": "Serbia",
        "PPP": "Australia",
        "PVD": "USA",
        "SCC": "USA",
        "PUS": "South Korea",
        "PBC": "Mexico",
        "PUB": "USA",
        "PXM": "Mexico",
        "PZO": "Venezuela",
        "POP": "Dominican Republic",
        "PVR": "Mexico",
        "XPK": "Canada",
        "PUY": "Croatia (Hrvatska)",
        "PUW": "USA",
        "PNQ": "India",
        "PUQ": "Chile",
        "PUJ": "Dominican Republic",
        "FNJ": "North Korea",
        "TAO": "China",
        "YQB": "Canada",
        "UEE": "Australia",
        "ZQN": "New Zealand",
        "UET": "Pakistan",
        "UIP": "France",
        "UIN": "USA",
        "UIO": "Ecuador",
        "RBA": "Morocco",
        "RYK": "Pakistan",
        "RFP": "French Polynesia",
        "YOP": "Canada",
        "RAJ": "India",
        "RDU": "USA",
        "IXR": "India",
        "RGI": "French Polynesia",
        "RGN": "Myanmar",
        "RAP": "USA",
        "RAR": "Cook Island",
        "RKT": "United Arab Emirates",
        "RAZ": "Pakistan",
        "RWP": "Pakistan",
        "RDG": "USA",
        "REC": "Brazil",
        "RDD": "USA",
        "RDM": "USA",
        "REG": "Italy",
        "YQR": "Canada",
        "TFS": "Spain",
        "RNS": "France",
        "RNO": "USA",
        "YRB": "Canada",
        "REU": "Spain",
        "KEF": "Iceland",
        "REK": "Iceland",
        "RHI": "USA",
        "RHO": "Greece",
        "RCB": "South Africa",
        "RIC": "USA",
        "RIX": "Latvia",
        "RJK": "Croatia (Hrvatska)",
        "RMI": "Italy",
        "RBR": "Brazil",
        "RIO": "Brazil",
        "GIG": "Brazil",
        "SDU": "Brazil",
        "RUH": "Saudi Arabia",
        "RNE": "France",
        "ROA": "USA",
        "RTB": "Honduras",
        "RST": "USA",
        "ROC": "USA",
        "RSD": "Bahamas",
        "RKS": "USA",
        "RFD": "USA",
        "ROK": "Australia",
        "RKD": "USA",
        "RWI": "USA",
        "RDZ": "France",
        "RRG": "Mauritius",
        "RNN": "Denmark",
        "ROM": "Italy",
        "CIA": "Italy",
        "FCO": "Italy",
        "RNB": "Sweden",
        "ROS": "Argentina",
        "ROV": "Russia",
        "RVI": "Russia",
        "ROT": "New Zealand",
        "RTM": "Netherlands",
        "RVN": "Finland",
        "NDU": "Namibia",
        "ROU": "Bulgaria",
        "SCN": "Germany",
        "SMF": "USA",
        "SDS": "Japan",
        "MBS": "USA",
        "SDT": "Pakistan",
        "SGN": "Vietnam",
        "SBK": "France",
        "RUN": "Reunion",
        "YSJ": "Canada",
        "SPN": "Northern Mariana Islands",
        "SID": "Cape Verde",
        "SLL": "Oman",
        "SLE": "USA",
        "SNC": "Ecuador",
        "SNS": "USA",
        "SAY": "Zimbabwe",
        "SBY": "USA",
        "SKG": "Greece",
        "SLC": "USA",
        "SLA": "Argentina",
        "SSA": "Brazil",
        "SZG": "Austria",
        "AZS": "Dominican Republic",
        "KUF": "Russia",
        "SKD": "Uzbekistan",
        "SMI": "Greece",
        "SZF": "Turkey",
        "ADZ": "Colombia",
        "SJT": "USA",
        "SAT": "USA",
        "BRC": "Argentina",
        "SAN": "USA",
        "SFO": "USA",
        "SJO": "Costa Rica",
        "SJD": "Mexico",
        "SJC": "USA",
        "SJU": "Puerto Rico",
        "SBP": "USA",
        "SLP": "Mexico",
        "SPY": "Cote d'Ivoire",
        "SAP": "Honduras",
        "SAL": "El Salvador",
        "ZSA": "Bahamas",
        "EAS": "Spain",
        "SAH": "Yemen",
        "YZP": "Canada",
        "SNA": "USA",
        "SBA": "USA",
        "SPC": "Spain",
        "SRZ": "Bolivia",
        "SKV": "Egypt",
        "SMA": "Portugal",
        "SMX": "USA",
        "RSA": "Argentina",
        "SRA": "Brazil",
        "SRB": "Bolivia",
        "STS": "USA",
        "SDH": "Honduras",
        "SRL": "Mexico",
        "SSL": "Colombia",
        "SDR": "Spain",
        "SCU": "Cuba",
        "SCL": "Chile",
        "SCQ": "Spain",
        "SON": "Vanuatu",
        "SDQ": "Dominican Republic",
        "SLZ": "Brazil",
        "SAO": "Brazil",
        "CGH": "Brazil",
        "GRU": "Brazil",
        "VCP": "Brazil",
        "TMS": "Sao Tome & Principe",
        "SPK": "Japan",
        "OKD": "Japan",
        "CTS": "Japan",
        "SJJ": "Bosnia and Herzegovina",
        "SKX": "Russia",
        "SRQ": "USA",
        "YXE": "Canada",
        "ZSS": "Cote d'Ivoire",
        "SAV": "USA",
        "SVL": "Finland",
        "TAB": "Trinidad and Tobago",
        "NSO": "Australia",
        "SCF": "USA",
        "SEA": "USA",
        "SEB": "Libya",
        "SJY": "Finland",
        "PKW": "Botswana",
        "SDJ": "Japan",
        "ICN": "South Korea",
        "SEL": "South Korea",
        "SVQ": "Spain",
        "SFA": "Tunisia",
        "ZTM": "Canada",
        "SHA": "China",
        "PVG": "China",
        "SNN": "Ireland",
        "SHJ": "United Arab Emirates",
        "SSH": "Egypt",
        "SZD": "United Kingdom",
        "DSA": "United Kingdom",
        "SHD": "USA",
        "SHE": "China",
        "SZX": "China",
        "SHR": "USA",
        "SHV": "USA",
        "JHQ": "Australia",
        "SBW": "Malaysia",
        "SDY": "USA",
        "SLS": "Bulgaria",
        "SIP": "Ukraine",
        "MPD": "Pakistan",
        "SIN": "Singapore",
        "QPG": "Singapore",
        "XSP": "Singapore",
        "SIX": "Australia",
        "SUX": "USA",
        "FSD": "USA",
        "SIS": "South Africa",
        "SIT": "USA",
        "VAS": "Turkey",
        "SEW": "Egypt",
        "SGY": "USA",
        "KDU": "Pakistan",
        "JSI": "Greece",
        "SKP": "Macedonia",
        "SKS": "Denmark",
        "SZK": "South Africa",
        "SXL": "Ireland",
        "YYD": "Canada",
        "SOT": "Finland",
        "SGD": "Denmark",
        "SFJ": "Greenland",
        "SOF": "Bulgaria",
        "SOG": "Norway",
        "SBN": "USA",
        "XSI": "Canada",
        "SOI": "Australia",
        "SOU": "United Kingdom",
        "SEN": "United Kingdom",
        "SPU": "Croatia (Hrvatska)",
        "GEG": "USA",
        "SBU": "South Africa",
        "SGF": "USA",
        "SPI": "USA",
        "SXR": "India",
        "YIF": "Canada",
        "STX": "Virgin Islands (U.S.)",
        "EBU": "France",
        "SGU": "USA",
        "YYT": "Canada",
        "SKB": "St. Kitts and Nevis",
        "STL": "USA",
        "UVF": "Saint Lucia",
        "SLU": "Saint Lucia",
        "SXM": "Netherlands Antilles",
        "SFG": "St. Martin (Guadeloupe)",
        "LED": "Russia",
        "FSP": "Canada",
        "STT": "Virgin Islands (U.S.)",
        "SVD": "Saint Vincent and the Grenadines",
        "STN": "United Kingdom",
        "SCE": "USA",
        "SVG": "Norway",
        "HDN": "USA",
        "SZZ": "Poland",
        "ARN": "Sweden",
        "BMA": "Sweden",
        "STO": "Sweden",
        "SCK": "USA",
        "SYY": "United Kingdom",
        "SXB": "France",
        "KBY": "Australia",
        "STR": "Germany",
        "SUL": "Pakistan",
        "SKZ": "Pakistan",
        "LSI": "United Kingdom",
        "SUN": "USA",
        "SDL": "Sweden",
        "MCY": "Australia",
        "SUB": "Indonesia",
        "STV": "India",
        "SUV": "Fiji",
        "SWP": "Namibia",
        "SYD": "Australia",
        "ZYL": "Bangladesh",
        "SYR": "USA",
        "TUU": "Saudi Arabia",
        "TIF": "Saudi Arabia",
        "TPE": "Taiwan",
        "TAY": "Taiwan",
        "TYN": "China",
        "TAK": "Japan",
        "TKA": "USA",
        "TLH": "USA",
        "QUF": "Estonia",
        "TLL": "Estonia",
        "TPA": "USA",
        "TMP": "Finland",
        "TAM": "Mexico",
        "TMW": "Australia",
        "TNG": "Morocco",
        "TRO": "Australia",
        "TGV": "Bulgaria",
        "TAS": "Uzbekistan",
        "TWU": "Malaysia",
        "TBS": "Georgia",
        "TEU": "New Zealand",
        "MME": "United Kingdom",
        "TGU": "Honduras",
        "THR": "Iran",
        "TEQ": "Turkey",
        "TLV": "Israel",
        "TEX": "USA",
        "TEM": "Australia",
        "TCI": "Spain",
        "TFN": "Spain",
        "TFS": "Spain",
        "TCA": "Australia",
        "TER": "Portugal",
        "THE": "Brazil",
        "TMZ": "Uzbekistan",
        "YXT": "Canada",
        "HUF": "USA",
        "TXK": "USA",
        "TCU": "South Africa",
        "YQD": "Canada",
        "SKG": "Greece",
        "TVF": "USA",
        "JTR": "Greece",
        "TRV": "India",
        "TED": "Denmark",
        "YTH": "Canada",
        "KTB": "USA",
        "YQT": "Canada",
        "TIS": "Australia",
        "TSN": "China",
        "TIJ": "Mexico",
        "TOD": "Indonesia",
        "TIA": "Albania",
        "TRZ": "India",
        "TIV": "Montenegro",
        "TAB": "Trinidad and Tobago",
        "TKS": "Japan",
        "TYO": "Japan",
        "HND": "Japan",
        "NRT": "Japan",
        "TOL": "USA",
        "TPR": "Australia",
        "TWB": "Australia",
        "YTO": "Canada",
        "YTZ": "Canada",
        "YYZ": "Canada",
        "TOV": "British Virgin Islands",
        "TOU": "New Caledonia",
        "TLS": "France",
        "TSV": "Australia",
        "TOY": "Japan",
        "TZX": "Turkey",
        "TPS": "Italy",
        "TVC": "USA",
        "TCB": "Bahamas",
        "TTN": "USA",
        "TSF": "Italy",
        "TRS": "Italy",
        "TIP": "Libya",
        "TOS": "Norway",
        "TRD": "Norway",
        "TSB": "Namibia",
        "TUS": "USA",
        "TUP": "USA",
        "TUL": "USA",
        "TUN": "Tunisia",
        "TUK": "Pakistan",
        "TRN": "Italy",
        "TKU": "Finland",
        "TCL": "USA",
        "TGZ": "Mexico",
        "TWF": "USA",
        "TYR": "USA",
        "UAH": "French Polynesia",
        "UAP": "French Polynesia",
        "UBJ": "Japan",
        "UBA": "Brazil",
        "UDI": "Brazil",
        "UBP": "Thailand",
        "UDR": "India",
        "UDE": "Netherlands",
        "UTH": "Thailand",
        "UFA": "Russia",
        "UHE": "Czech Republic",
        "UGO": "Angola",
        "UPG": "Indonesia",
        "UCT": "Russia",
        "UKI": "USA",
        "ULN": "Mongolia",
        "HLH": "China",
        "UUD": "Russia",
        "ULB": "Vanuatu",
        "USN": "South Korea",
        "ULD": "South Africa",
        "UME": "Sweden",
        "YUD": "Canada",
        "UTT": "South Africa",
        "UNK": "USA",
        "UNI": "Saint Vincent and the Grenadines",
        "UNT": "United Kingdom",
        "UPL": "Costa Rica",
        "JUV": "Greenland",
        "UTN": "South Africa",
        "UPP": "USA",
        "YBE": "Canada",
        "UGC": "Uzbekistan",
        "URM": "Venezuela",
        "OMH": "Iran",
        "UPN": "Mexico",
        "URB": "Brazil",
        "URG": "Brazil",
        "URC": "China",
        "URZ": "Afghanistan",
        "USH": "Argentina",
        "UTP": "Thailand",
        "UCA": "USA",
        "UII": "Honduras",
        "UMD": "Greenland",
        "UDJ": "Ukraine",
        "VAA": "Finland",
        "VXO": "Sweden",
        "EGE": "USA",
        "YVO": "Canada",
        "VDZ": "USA",
        "VLD": "USA",
        "VLC": "Spain",
        "VLN": "Venezuela",
        "VLL": "Spain",
        "VAP": "Chile",
        "VDE": "Spain",
        "VAN": "Turkey",
        "YVR": "Canada",
        "VRA": "Cuba",
        "VNS": "India",
        "VRK": "Finland",
        "VAR": "Bulgaria",
        "VST": "Sweden",
        "VLU": "Russia",
        "VCE": "Italy",
        "VER": "Mexico",
        "VEL": "USA",
        "VRB": "USA",
        "VRN": "Italy",
        "VBS": "Italy",
        "YYJ": "Canada",
        "VFA": "Zimbabwe",
        "VID": "Bulgaria",
        "VTE": "Lao PDR",
        "VGO": "Spain",
        "VSA": "Mexico",
        "VNO": "Lithuania",
        "VIJ": "Virgin Islands (British)",
        "VIS": "USA",
        "VBY": "Sweden",
        "VIT": "Spain",
        "VIX": "Brazil",
        "VYD": "South Africa",
        "YWK": "Canada",
        "ACT": "USA",
        "WGA": "Australia",
        "ALW": "USA",
        "WLS": "Wallis and Futuna Islands",
        "WVB": "South Africa",
        "WMB": "Australia",
        "WAW": "Poland",
        "WAS": "USA",
        "IAD": "USA",
        "DCA": "USA",
        "BWI": "USA",
        "ALO": "USA",
        "ATY": "USA",
        "CWA": "USA",
        "WEI": "Australia",
        "WEL": "South Africa",
        "WLG": "New Zealand",
        "EAT": "USA",
        "PBI": "USA",
        "WYS": "USA",
        "GWT": "Germany",
        "WHK": "New Zealand",
        "YXN": "Canada",
        "WRE": "New Zealand",
        "HPN": "USA",
        "YXY": "Canada",
        "HAP": "Australia",
        "WYA": "Australia",
        "ICT": "USA",
        "SPS": "USA",
        "WIC": "United Kingdom",
        "WHM": "Australia",
        "VIE": "Austria",
        "WIE": "Germany",
        "AVP": "USA",
        "IPT": "USA",
        "ISL": "USA",
        "ILM": "USA",
        "VNO": "Lithuania",
        "WUN": "Australia",
        "WDH": "Namibia",
        "ERS": "Namibia",
        "YQG": "Canada",
        "YWG": "Canada",
        "OLF": "USA",
        "WOL": "Australia",
        "UMR": "Australia",
        "ORH": "USA",
        "WRL": "USA",
        "WRG": "USA",
        "WUH": "China",
        "WYN": "Australia",
        "XMN": "China",
        "XIY": "China",
        "YKM": "USA",
        "YAK": "USA",
        "YKS": "Russia",
        "GAJ": "Japan",
        "ASK": "Côte d'Ivoire",
        "YNB": "Saudi Arabia",
        "RGN": "Myanmar",
        "YAO": "Cameroon",
        "SVX": "Russia",
        "YZF": "Canada",
        "YIH": "China",
        "YOK": "Japan",
        "YUM": "USA",
        "ZCL": "Mexico",
        "ZAD": "Croatia (Hrvatska)",
        "ZAG": "Croatia (Hrvatska)",
        "ZTH": "Greece",
        "ZAZ": "Spain",
        "PZH": "Pakistan",
        "ZND": "Niger",
        "OUZ": "Mauritania",
        "ZRH": "Switzerland"
    }

    if (direction == "A") {
        return {
            arrivalCity: "Netherlands",
            departureCity: countries[IATA]
        }
    } else if (direction == "D") {
        return {
            arrivalCity: countries[IATA],
            departureCity: "Netherlands"
        }
    } else return
}

// uçuşun yönüne göre airportIATA kodlarının atanması.
export function getAirportIATA(direction, destination) {
    if (direction == "A") {
        return {
            // Kalkış
            departureIATA: destination,
            // İniş 
            arrivalIATA: "AMS"
        }
    } else if (direction == "D") {
        return {
            // Kalkış
            departureIATA: "AMS",
            // İniş 
            arrivalIATA: destination
        }
    } else return

}

// veritabanında UTC formatındaki zamanın istenilen formata çevrilmesi.
export function formatTime(dateTime) {
    // gelen zamanı date nesnesine dönüştür.
    const date = new Date(dateTime);

    // saat ve dakikayı al.
    let hour = date.getUTCHours();
    let minute = date.getUTCMinutes();

    // am ve pm belirleme.
    const ampm = hour >= 12 ? 'PM' : 'AM';

    // 12 saat formatına dönüştür.
    hour = hour % 12;
    hour = hour === 0 ? 12 : hour;

    // saat ve dakikayı iki basamaklı formata çevir.
    const formattedHour = hour < 10 ? `0${hour}` : hour;
    minute = minute < 10 ? `0${minute}` : minute;

    return `${formattedHour}:${minute} ${ampm}`
}